### ISSUE TITLE
Example / Syntax error

### ISSUE THREAD

**Issue by yourabi** [SimpleFinance/java#17]
Hi!

Is this cookbook ready / in use? The example config doesn't parse...

Thanks!

**Comment by jdinthe** [comment]
Hey @yourabi, we do use it internally for one case. I haven't dug into this cookbook much. Probably @miah has the best insight here.

**Comment by yourabi** [comment]
@jakedavis  Thanks for the info/clarification. If possible it would be great to see a snippet of your usage...maybe I'm goofing here.

Thanks again for all your help!

**Comment by miah** [comment]
The readme has been updated. The included test-kitchen cookbook and tests should prove that it works.

**Comment by yourabi** [comment]
Thanks!
